### ISSUE TITLE
[Feature Request] Mods loading support

### ISSUE THREAD

**Issue by begin-theadventure** [p0358/black_market_edition#3]
https://github.com/R1Spectre/Spectre

**Comment by p0358** [comment]
I mean technically I could copy-paste mod support from TFORevive, similar to how Northstar mods work, but would it be worth it? Only TFORevive has a launcher that allows people to list and disable mods, and the in-game menu, while here players would have to edit JSON manually? Wouldn't it be better for BME to just have a single folder where you could dump in the files you want to replace for instance? (Also the presence of VPK system alone makes some types of files trickier to replace...)

**Comment by begin-theadventure** [comment]
Would it be impossible or too difficult to add an in-game mod list or commands to manage mods (mod list, mod disable/enable)?
If so, disabling mods wouldn't be a huge problem anyway, since one could simply move the mod they want to disable to another folder.
I'm aware that there will be TFORevive, but I think it would be great to also have such an option with the original Titanfall.
As for dumping the files into one folder, that would be messy and cause conflicts, for example in the case of keyvalues.

**Comment by p0358** [comment]
> Would it be impossible or too difficult to add an in-game mod list or commands to manage mods (mod list, mod disable/enable)?

Eh, maybe that'd be doable with reasonable effort...

> As for dumping the files into one folder, that would be messy and cause conflicts, for example in the case of keyvalues.

KeyValues would overwrite one another in accordance with mod loading order either way without a special handling, and I'm 100% not backporting that, as KV overrides code is gonna be somewhat complex probably (also it's not yet written in TFOR xD; and I won't copy-paste it from Northstar as I don't like how they do it + their method wouldn't work as-is for us either I think...)

**Comment by p0358** [comment]
Now `r1_mod` dir feature is available in v1b11, this is the most that will happen in BME, as one can otherwise easily patch VPKs with Harmony VPK Tool too, and all of the current ongoing coding efforts shall be directed at TFORevive instead...
